---
title: "Gradescope"
author: "David Kane and Tyler Simko"
date: "6/9/2020"
output: html_document
---

Gradescope is an automated grading software service that allows instructors to input rubrics and control scoring. It can connect to Canvas and Github, and grades can be released with the click of a button. Implementing Gradescope will free up CA/TF time and also allow for consistency in pset/exam grading. The most work that will be required (once I figure out how to run this on Windows) will be writing the grading scripts.

## Resources

Gradescope Resources

* [Autograder specifications](https://gradescope-autograders.readthedocs.io/en/latest/specs/) runs through the file hierarchy of necessary autograder files, how to run a test assignment, and how to deploy the actual autograder itself. Really useful resource.

* Tutorial on [simple grading walkthrough](https://www.youtube.com/watch?v=F2e9AK7pNFY&feature=emb_logo) from the instructor's POV 

External Resources

* Jeremy from HUIT's [autograding script repo](https://github.com/jaguillette/r_autograde_gradescope/tree/master/r_script)
    + This doesn't work well for Windows systems bc setup.sh is in Linux
* [Tufts Gradescope guide](http://systems.eecs.tufts.edu/wp-content/uploads/sites/5/2018/11/Gradescope_Instructions.pdf) dives into autograding and what the different files are actually for 

## How to Autograde in Gradescope (In Theory)

Steps

1. Log in to Gradescope through **School Credentials* and select HarvardKey.
2. Assignments -> Programming Assignment -> Create Assignment and input details on the title of the assignment, the date assigned, etc.
    + Customize release date of assignment, assignment due date, late submission deadline, and autograding point scale
3. Configure the Autograder by uploading appropriate files in zipped version and press 'Update Autograder'
    + Toggle the visibility of test cases by adding in "visibility":"after_due_date", "hidden", "after_published"
    + Each time the autograder is changed, it need to be re-uploaded and the Docker image will be rebuilt, according to [Michael Guerzhoy](https://github.com/guerzh/r_autograde_gradescope). This is annoying because it took 15 minutes to finish running the simple autograder from Jeremy, We get around re-building the Docker image by adding `wget https://[your server/autograde_ps1.R` to `run_autograder`.
4. Test Autograder by uploading a sample response (relevant options are from computer or Github)
5. Deploy autograder!
    + [Autograde materials](https://github.com/jaguillette/r_autograde_gradescope/tree/master/r_script)

Autograding files

* setup.sh - a bash script that enables the autograding machine by installing all necessary dependencies/files (Gradescope uses Ubuntu 18.04 images)
* run_autograder - commands that actually run the autograding script
* autograde_ps1 (or something similarly named) - the script that outputs the correct answers 
* results - the json output file, which Gradescope will use to compare students' responses with the answer template

## Autograding in Gradescope (In Practice)

Rscript Trial

1. Set up [XID](xid.harvard.edu) in order to access the Github Classroom as a separate student user (for testing purposes)
    + See Outstanding Roadblocks
2. I'm getting the error *cp: cannot stat '/autograder/submission/ps1.R': No such file or directory* which most definitely has to do with file locations. It's hard to work with because the Docker image re-builds every time I re-upload the autograder, so my next steps are first figuring out how to prevent the image from rebuilding every time using command line magic.
3. Upon further inspection, it seems like the problem is coming from setup.sh, the file that installs the necessary packages (jsonlite, gapminder etc.) because the file is in Linux and Linux is incompatible with Windows command line. I would need a Mac user to test if the files work for them, but I want to find a Windows solution for now. As I see it, I (and any Windows-using TFs of the future) have two options:
      a. Download a Windows Linux subsystem and attempt to run from there; or
      b. Understand what setup.sh does and re-write the code to make it compatible for Windows command line
4. I'm now installing the [Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10?redirectedfrom=MSDN)
      a. Run `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart` from Windows Powershell as administrator. Restart computer.
      b. Navigate to Windows Store and download Ubuntu. Click 'Install' to let it initialize
      c. Run `wsl --set-version Ubuntu 1` in Powershell

The Linux subsystem installation was probably unnecessary, only necessary if you want to run the files locally. I received an error message that has to deal with the actual code of the Rscript itself (an ungrouping error), so I tweaked the code of the answer pset and managed to get the autograder to work! 

Rmarkdown trial

1. Following the same steps as before, except placing Ps1.R code into a Markdown titled Ps1.Rmd. One thing to note: The autograding function is extremely picky, and it is case sensitive to the file name of the submission (i.e. ps1.R would work, but Ps1.R wouldn't).
2. Replace all instances of "ps1.R" with "ps1.Rmd" in `setup` and `run_autograder.R`. 
3. I received this error message:
`Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available)`
which means that the `pandoc` package was missing from the Docker image, so I'm referring to [this repo](https://github.com/thomasWeise/docker-pandoc/blob/master/image/Dockerfile) to figure it out.
      + Other resources I'm looking at are the[ official Pandoc website](https://pandoc.org/installing.html#docker) and [repo](https://github.com/pandoc/dockerfiles#basic-usage) since the Thomas Weise Docker image didn't work


Using Github

1. I'm using the same autograder for the Rscript just to get things going.
2. When uploading a file to test the autograder, select the Github option. It will ask you to log in and authorize access to private and public repos. Here you can also grant Gradescope organizational access (I can currently grant gov 1005 access based off of my CA status). It will also ask you to select a repository and select a branch of that repositoryI put the test submission in a private repo for now.
3. This works upon running! Next, it would be helpful to have access to an XID/ student account so I can see how students would submit their work (They may have to each individually link to their pset repo).


## Oustanding Roadblocks

1. XID access so I can submit an assignment and view the process from the student end (Gradescope has a test autograder function but it's best to check from the POV of a student)
      + I've been transferred to someone from HUIT, who has told me in a back-and-forth that I don't need an XID because HUID has more permissions, but still not sure how I can view the class completely as a student. I will be calling them on Monday to figure this out: (617) 495-7777.
